version: '3.3'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: pgoel
      POSTGRES_PASSWORD: 89910331
      POSTGRES_DB: pgdb
    ports:
      - "5432:5432"
    networks:
      - app-network

  emp-cache-service:
    build:
      context: ./employee-cache-service
    container_name: emp-cache-service
    depends_on:
      - redis
    environment:
      SPRING_REDIS_HOST: redis
    ports:
      - "8082:8082"
    networks:
      - app-network

  emp-scheduler-service:
    build:
      context: ./employee-scheduler-service
    container_name: emp-scheduler-service
    depends_on:
      - postgres
      - redis
      - emp-cache-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pgdb
      SPRING_REDIS_HOST: redis
    ports:
      - "8083:8083"
    networks:
      - app-network

  emp-query-service:
    build:
      context: ./employee-query-service
    container_name: emp-query-service
    depends_on:
      - postgres
      - emp-cache-service
      - emp-scheduler-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pgdb
    ports:
      - "8084:8084"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

